name = "RushLarsenSolvers"
uuid = "b6f3d1c9-8097-4b1b-8f54-e3bff95fe181"
version = "1.0.0-DEV"
authors = ["jClugstor <jadonclugston@gmail.com> and contributors"]

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ConcreteStructs = "0.2.3"
DiffEqBase = "6.183.2"
LinearAlgebra = "1.6.7"
MuladdMacro = "0.2.4"
OrdinaryDiffEq = "6.89.0"
Parameters = "0.12.3"
Reexport = "1.2.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
